services:
  flask-app:
    build: .
    container_name: hello-flask
    restart: always
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app