pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Coletinn/hello-flask.git'
            }
        }
        stage('Set Up Python Virtual Environment') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }
        stage('Run Flask App') {
            steps {
                sh '. venv/bin/activate && python app.py'
            }
        }
    }
}
