pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t flask-hello app/
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker run -d -p 5000:5000 --name hello-flask-app hello-flask-app
                '''
                echo 'Aplicação Flask rodando em http://localhost:5000'
            }
        }
    }

    post {
        always {
            echo 'Encerrando container...'
            sh 'docker rm -f hello-flask-app || true'
        }
    }
}
