name: Deploy Docker Flask App to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/hello-flask
          
          git pull origin main
          
          docker compose down
          docker compose up -d --build
          
          sleep 5
          
          docker compose ps
          
          docker compose logs --tail=20
          
          echo "Deploy concluído em $(date)"